version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
